# Generated by Django 4.2.16 on 2024-10-09 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.coach'),
        ),
    ]
