# Generated by Django 4.2.16 on 2024-10-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='coach',
            field=models.CharField(blank=True, choices=[('John Doe', 'John Doe'), ('Jane Smith', 'Jane Smith'), ('Alex Johnson', 'Alex Johnson')], max_length=100, null=True),
        ),
    ]
