# Generated by Django 4.2.16 on 2024-10-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='coach',
            field=models.CharField(choices=[('Brad Hammond', 'Brad Hammond'), ('Joe Bloggs', 'Joe Bloggs'), ('Jane Doe', 'Jane Doe')], default='Brad Hammond', max_length=100),
            preserve_default=False,
        ),
    ]
