# Generated by Django 4.2.16 on 2024-10-11 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_coach'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'permissions': [('can_accept_booking', 'Can accept booking')]},
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
