# Generated by Django 4.2.16 on 2024-10-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_coach_feedback_alter_booking_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'permissions': [('can_accept_booking', 'Can accept booking'), ('can_delete_booking', 'Can delete booking')]},
        ),
    ]
